### ISSUE TITLE
Redirects from geosciml.org/ontology and geosciml.org/vocabulary need fixing

### ISSUE THREAD

**Issue by dr-shorthair** [CGI-IUGS/geosciml.org#3]
http://resource.geosciml.org/ontology/timescale/gts 
--> https://raw.githack.com/CGI-IUGS/timescale-ont/master/html/gts.html for Accept: text/html
--> https://raw.githack.com/CGI-IUGS/timescale-ont/master/rdf/gts.ttl if Accept: text/turtle

http://resource.geosciml.org/vocabulary/timescale/
--> https://github.com/CGI-IUGS/timescale-data probably

**Comment by dr-shorthair** [comment]
Also: 
http://resource.geosciml.org/ontology/timescale/thors
--> https://raw.githack.com/CGI-IUGS/timescale-ont/master/html/thors.html for Accept: text/html
--> https://raw.githack.com/CGI-IUGS/timescale-ont/master/rdf/thors.ttl if Accept: text/turtle

**Comment by shyni-s** [comment]
Hi @dr-shorthair, will you please assign this to wjfrancis? I couldn't assign this to him as he's not part of the project.
Cheers,
Shyni

**Comment by dr-shorthair** [comment]
@shyni-s I can't because Will has not accepted his invitation to join this organization. I'll re-issue the invitation, and perhaps you can prompt him?

**Comment by dr-shorthair** [comment]
The issue has been resolved anyway.

**Comment by shyni-s** [comment]
@dr-shorthair I'll remind him.
